version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080

  db:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=pass
    ports:
      - 5432:5432

